# -*- coding: utf-8 -*-

from . import qr_generator
from . import hr_action_joining
from . import hr_action_clearance
from . import hr_action_absence
from . import hr_action_leave_return
from . import hr_leave
from . import hr_skills
from . import hr_employee
from . import care_hr_employee_ext
from . import care_job_grade
from . import care_manpower_file
from . import care_penalty
from . import care_allowance
from . import care_violation_type
from . import care_violation
from . import care_coverage
from . import care_passport
from . import care_skills
from . import care_lifecycle
from . import care_operations
from . import care_finance
from . import care_governance
from . import care_billing
from . import care_welfare
from . import care_analytics
from . import care_sla
from . import care_loan
from . import care_hostel
from . import care_dept_link
from . import care_i18n
from . import care_menu_setup
from . import care_grievance
from . import care_custody
from . import care_gov_transaction
from . import care_site_permit
from . import care_absconding
from . import care_access_profile
from . import care_announcement
from . import care_payslip
from . import care_allowance_payout
from . import care_config_settings
from . import res_users
