{
    'name': 'Purchase Custom Report',
    'version': '17.0',
    'sequence': '1',
    'summary': 'Purchase Custom Report',
    'description': 'Purchase Custom Report',
    'category': '',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'purchase', 'hr', 'care', 'project'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/sequence.xml',
        'data/mail_template_data.xml',
        'views/res_company.xml',
        'views/purchase_inherit_view.xml',
        'views/purchase_request.xml',
        'views/cost_center.xml',
        'reports/purchase_report.xml',
        'reports/purchase_request_report.xml',
        'reports/purchase_report_header.xml',
        'reports/employee_contract_arabic.xml',
        'reports/employee_contract_english.xml',
        'reports/employee_contract_english_renew.xml',
        'wizards/arrival_resident.xml',
        'views/hr_employee.xml',
        'views/social_contract.xml',
        'views/res_config_settings.xml',
        'views/default_sign_employee.xml',
        'reports/arrival_resident_report.xml',
        'reports/purchase_quotation.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False
}
