{
    "name": "Service Order",
    "summary": "Service Order",
    "version": "15.0.0.0.0",
    "category": "Other",
    "license": "LGPL-3",
    "data": [
        "security/ir.model.access.csv",
        "data/service_service.xml",
        "views/service_service_views.xml",
        "views/service_center_tag_views.xml",
        "views/service_item_tag_views.xml",
        "views/service_order_tag_views.xml",
        "views/service_project_tag_views.xml",
        "views/service_pickup_location_tag_views.xml",
        "views/service_trip_tag_views.xml",
        "views/service_project_views.xml",
        "views/service_type_views.xml",
        "views/service_item_views.xml",
        "views/service_center_views.xml",
        "views/service_team.xml",
        "views/service_pickup_location_views.xml",
        "views/service_order_views.xml",
        "views/service_trip_views.xml",
        "views/portal/service_order_portal.xml",
        "views/portal/portal_service_order_list.xml",
        "views/portal/portal_service_order_create.xml",
        "views/portal/portal_service_order_details.xml",
        "views/portal/portal_service_order_update.xml",
        "reports/service_trip_report.xml",
    ],
    "depends": [
        "base",
        "mail",
        "hr",
        "portal",
        "report_xlsx_dynamic",
        "website",
    ],
    'assets': {
        'web.report_assets_common': ['service_order/static/src/css/service_trip_style.css',],
        'web.assets_frontend': ['service_order/static/src/css/service_trip_style.css',],
    }
}
