# -*- coding: utf-8 -*-
{
    'name': 'CARE Project Management System',
    'version': '17.0.1.0',
    'summary': 'Central projects/contracts hub: tasks, kinds, forwarding, groups, portal, dashboards',
    'author': 'CARE',
    'depends': ['project', 'hr', 'mail', 'fleet', 'care_experience', 'portal', 'website', 'purchase_report', 'sale', 'account'],
    'data': [
        'security/pms_groups.xml',
        'security/ir.model.access.csv',
        'security/pms_rules.xml',
        'data/sequences.xml',
        'data/pms_data.xml',
        'reports/pms_reports.xml',
        'views/task_category_views.xml',
        'views/pms_employee_views.xml',
        'views/task_group_views.xml',
        'views/materials_views.xml',
        'views/pettycash_views.xml',
        'views/docrequest_views.xml',
        'views/tasktemplate_views.xml',
        'views/project_views.xml',
        'views/task_views.xml',
        'views/portal_templates.xml',
        'views/portal_pm_templates.xml',
        'views/pms_menus.xml',
        'views/supply_views.xml',
        'views/order_button_views.xml',
        'data/crons.xml',
        'data/apply_i18n.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'care_pms/static/src/dashboard/pms_dashboard.scss',
            'care_pms/static/src/dashboard/pms_dashboard.js',
            'care_pms/static/src/dashboard/pms_dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
